/**
 * Executor Lifecycle Manager
 * Handles building, starting, stopping, and health-checking AD4M executor instances.
 */

import { spawn, ChildProcess, execSync } from "child_process";
import { mkdirSync, existsSync, writeFileSync, rmSync } from "fs";
import { join } from "path";
import WebSocket from "ws";

export interface ExecutorConfig {
  branch: string;
  port: number;
  dataPath: string;
  adminToken: string;
  adamRepoPath: string;
  buildDir: string;
  /** Extra CLI args appended to the `run` invocation (e.g. ["--language-language-only","true"]). */
  extraArgs?: string[];
}

export interface ExecutorInstance {
  config: ExecutorConfig;
  process: ChildProcess | null;
  binaryPath: string;
  buildDurationMs: number;
  startDurationMs: number;
}

export async function buildExecutor(config: ExecutorConfig): Promise<string> {
  const { branch, buildDir, adamRepoPath } = config;

  console.log(`[executor] Building branch: ${branch} in ${buildDir}`);

  if (existsSync(buildDir)) {
    rmSync(buildDir, { recursive: true, force: true });
  }

  execSync(
    `git clone --depth 1 --branch ${branch} --single-branch "${adamRepoPath}" "${buildDir}"`,
    { stdio: "pipe", timeout: 60000 }
  );

  // Ensure dapp/dist placeholder exists
  const dappDir = join(buildDir, "dapp", "dist");
  mkdirSync(dappDir, { recursive: true });
  if (!existsSync(join(dappDir, "index.html"))) {
    writeFileSync(join(dappDir, "index.html"), "<!DOCTYPE html><html><body></body></html>");
  }

  // CUSTOM_DENO_SNAPSHOT.bin must exist for the executor's `include_bytes!` to
  // compile, but it must also be regenerated against the build's own
  // deno_runtime version — V8 panics with a magic-number mismatch otherwise.
  // Seed a stub (or copy a cached snapshot if one exists) so the snapshot
  // generator binary compiles, then run it to produce a fresh snapshot in
  // place. The subsequent executor build picks up the regenerated bytes.
  const snapshotSrc = join(adamRepoPath, "CUSTOM_DENO_SNAPSHOT.bin");
  const snapshotRustExecutorPath = join(buildDir, "rust-executor", "CUSTOM_DENO_SNAPSHOT.bin");
  const snapshotRootPath = join(buildDir, "CUSTOM_DENO_SNAPSHOT.bin");
  if (existsSync(snapshotSrc)) {
    execSync(`cp "${snapshotSrc}" "${snapshotRootPath}"`, { stdio: "pipe" });
    execSync(`cp "${snapshotSrc}" "${snapshotRustExecutorPath}"`, { stdio: "pipe" });
  } else {
    writeFileSync(snapshotRootPath, "");
    writeFileSync(snapshotRustExecutorPath, "");
  }

  // Copy schema.gql if needed
  const schemaSrc = join(adamRepoPath, "core", "lib", "src", "schema.gql");
  if (existsSync(schemaSrc)) {
    const schemaTarget = join(buildDir, "core", "lib", "src");
    mkdirSync(schemaTarget, { recursive: true });
    execSync(`cp "${schemaSrc}" "${join(schemaTarget, "schema.gql")}"`, { stdio: "pipe" });
  }

  // Regenerate CUSTOM_DENO_SNAPSHOT.bin from the branch's own sources.
  console.log(`[executor] Regenerating CUSTOM_DENO_SNAPSHOT.bin for ${branch}...`);
  execSync("cargo run --release --bin generate_snapshot 2>&1", {
    cwd: join(buildDir, "rust-executor"),
    stdio: "pipe",
    timeout: 1800000, // 30 min
  });
  // The generator writes the file relative to its cwd (rust-executor/);
  // mirror it to the workspace root so both include_bytes paths see it.
  execSync(`cp "${snapshotRustExecutorPath}" "${snapshotRootPath}"`, { stdio: "pipe" });

  // Build the executor
  console.log(`[executor] Building ad4m-executor for ${branch}...`);
  execSync("cargo build --release --bin ad4m-executor 2>&1", {
    cwd: buildDir,
    stdio: "pipe",
    timeout: 1800000, // 30 min
  });

  const binaryPath = join(buildDir, "target", "release", "ad4m-executor");
  if (!existsSync(binaryPath)) {
    throw new Error(`Binary not found at ${binaryPath}`);
  }

  console.log(`[executor] Build complete: ${binaryPath}`);
  return binaryPath;
}

export async function initExecutor(binaryPath: string, dataPath: string): Promise<void> {
  // Clean data directory
  if (existsSync(dataPath)) {
    rmSync(dataPath, { recursive: true, force: true });
  }
  mkdirSync(dataPath, { recursive: true });

  // Run init
  console.log(`[executor] Initializing data at ${dataPath}...`);
  execSync(`"${binaryPath}" init --data-path "${dataPath}" 2>&1`, {
    stdio: "pipe",
    timeout: 30000,
  });
}

export async function startExecutor(
  binaryPath: string,
  config: ExecutorConfig
): Promise<ChildProcess> {
  // Initialize if needed
  await initExecutor(binaryPath, config.dataPath);

  console.log(`[executor] Starting on port ${config.port}, data: ${config.dataPath}`);

  const proc = spawn(binaryPath, [
    "run",
    "--app-data-path", config.dataPath,
    "--port", String(config.port),
    "--admin-credential", config.adminToken,
    "--run-dapp-server", "false",
    "--hc-use-bootstrap", "false",
    "--hc-use-proxy", "false",
    ...(config.extraArgs ?? []),
  ], {
    stdio: ["pipe", "pipe", "pipe"],
    env: { ...process.env, RUST_LOG: "info" },
  });

  proc.stdout?.on("data", (d) => {
    const line = d.toString().trim();
    if (line && process.env.VERBOSE) console.log(`[exec:${config.port}:out] ${line}`);
  });
  proc.stderr?.on("data", (d) => {
    const line = d.toString().trim();
    if (line && process.env.VERBOSE) console.log(`[exec:${config.port}:err] ${line}`);
  });

  return proc;
}

export async function waitForHealth(
  port: number,
  timeoutMs: number = 60000,
  adminToken: string = "test123"
): Promise<number> {
  const start = performance.now();
  const deadline = start + timeoutMs;

  const healthUrl = `http://127.0.0.1:${port}/health`;

  while (performance.now() < deadline) {
    try {
      const res = await fetch(healthUrl);
      if (res.ok) {
        // Also verify WS endpoint is accepting connections
        const wsReady = await checkWsReady(port, adminToken, 5000).catch(() => false);
        if (!wsReady) {
          await sleep(500);
          continue;
        }
        return performance.now() - start;
      }
    } catch {}
    await sleep(500);
  }

  throw new Error(`Executor on port ${port} did not become healthy within ${timeoutMs}ms`);
}

async function checkWsReady(port: number, token: string, timeoutMs: number): Promise<boolean> {
  return new Promise((resolve) => {
    const ws = new WebSocket(`ws://127.0.0.1:${port}/api/v1/ws?token=${token}`);
    const timer = setTimeout(() => { ws.close(); resolve(false); }, timeoutMs);
    ws.on("open", () => {
      // Send a lightweight RPC call to verify the executor is actually ready
      const id = "health-check-1";
      ws.send(JSON.stringify({ id, type: "agent.status", params: {} }));
    });
    ws.on("message", (data: any) => {
      try {
        const msg = JSON.parse(data.toString());
        if (msg.id === "health-check-1") {
          clearTimeout(timer);
          ws.close();
          resolve(true);
        }
      } catch {}
    });
    ws.on("error", () => { clearTimeout(timer); ws.close(); resolve(false); });
  });
}

export function stopExecutor(proc: ChildProcess): void {
  if (proc && !proc.killed) {
    proc.kill("SIGTERM");
    setTimeout(() => {
      if (!proc.killed) proc.kill("SIGKILL");
    }, 5000);
  }
}

export function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
